apiVersion: v1
kind: Secret
metadata:
  name: mysecret-example
type: Opaque
# data: # use the data method is base64 encoding is installed on local machine/dev machine
#   accesskey: accesskey
#   password: pass1234
stringData: # use this method and kubernetes will encode with base64 automatically once kubectl create is run
  accesskey: "accessKey"
  pass: "1234password"
