apiVersion: skaffold/v1beta2
kind: Config
build: 
  local: 
    push: false # whenever an image is built, skaffold wants to push automatically
  artifacts:
    - image: bryjos44/clientimage # image I want to use
      context: directoryofimage # directory of dockerfile location
      docker:
        dockerfile: Dockerfile.dev # name of dockerfile to use
      sync:
        '**/*.js': . # what kind of files to use in local cluster for dev
        '**/*.css': .
        '**/*.html': .
    - image: bryjos44/serverimage
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
    - image: bryjos44/workerimage
      context: workerdirectory
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml # the config files we want skaffold to manage (k8s yaml files)
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml